import Head from 'next/head'
import { SquarePaymentsForm } from 'react-square-web-payments-sdk'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <SquarePaymentsForm
          applicationId="sandbox-sq0idb-EUptF0ceVgGoywxgupxKow"
          locationId="LVZPFGEJRQQ0R"
          cardTokenizeResponseReceived={}
        >
          
        </SquarePaymentsForm>
      </main>
    </div>
  )
}
