// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import { Client } from 'square';
import { randomUUID } from 'crypto';
BigInt.prototype.toJSON = function() { return this.toString(); }

const { paymentsApi } = new Client({
  accessToken: process.env.SQUARE_ACCESS_TOKEN,
  environment: 'sandbox',
}) 

export default async function handler(req, res) {
  if ( req.method === 'POST' ) {
    const { result } = await paymentsApi.createPayment({
      // An idempotency key is a unique value generated by the client 
      // which the resource server uses to recognize subsequent retries of the same request.
      idempotencyKey: randomUUID(),
      sourceId: req.body.sourceId,
      amountMoney: {
        currency: 'USD',
        amount: 100
      }
    })
    console.log(result);
    res.status(200).json(result);
  } else {
    res.status(500).send();
  }
}
